# Generated by Django 3.2 on 2021-05-14 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_approved',
        ),
    ]
